
server:
  port: 9092

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/backendModelsis
    username: username
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
